# Generated by Django 5.0.6 on 2024-06-29 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "department_id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="department_id",
                    ),
                ),
                ("dep_name", models.CharField(max_length=250)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "product_id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="product_id",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "customer_id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="customer_id",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("product", models.ManyToManyField(to="api.product")),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "student_id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="student_id",
                    ),
                ),
                ("stud_name", models.CharField(max_length=250)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.department",
                        verbose_name="department_id",
                    ),
                ),
            ],
        ),
    ]
